FROM akisatok/miniconda3-base
LABEL maintainer='akisatok <akisato@ieee.org>'
LABEL Description='An extension of the official miniconda3 Docker image for the use of pytorch.'

# pytorch
RUN conda install --quiet --yes -c pytorch pytorch torchvision
